[package]
name = "dherman"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
jsonschema = "0.37.4"
sacp = "2.0.0"
sacp-conductor = "4.0.0"
sacp-proxy = "3.0.0"
sacp-tokio = "2.1.0"
schemars = "1.1.0"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
